# Generated by Django 4.2.7 on 2026-03-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        help_text="Full name of the lead.", max_length=120
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Contact email for follow-up.", max_length=254
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True, help_text="Optional message from the lead."
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the lead was submitted."
                    ),
                ),
            ],
        ),
    ]
