# Generated by Django 4.2.7 on 2026-07-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsultationInquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=50)),
                (
                    "package",
                    models.CharField(
                        choices=[
                            ("consultation_booking", "Consultation booking - R100"),
                            ("hourly_consultation", "Hourly consultation - R250/hour"),
                            ("haircut_retainer", "Haircut retainer - R100/month"),
                            ("full_retainer", "Haircut + consultation retainer - R350/month"),
                        ],
                        max_length=32,
                    ),
                ),
                ("preferred_date", models.DateField(blank=True, null=True)),
                ("preferred_time", models.CharField(blank=True, max_length=80)),
                ("notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("awaiting_payment", "Awaiting payment"),
                            ("paid", "Paid"),
                            ("scheduled", "Scheduled"),
                        ],
                        default="new",
                        max_length=24,
                    ),
                ),
                (
                    "estimated_amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True),
                ),
            ],
        ),
    ]