# Generated by Django 4.2.7 on 2026-07-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0002_consultationinquiry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consultationinquiry",
            name="package",
            field=models.CharField(
                choices=[
                    ("hourly_consultation", "Hourly consultation - R250/hour"),
                    ("haircut_retainer", "Haircut - R100/month"),
                    ("full_retainer", "Haircut + consultation retainer - R350/month"),
                ],
                max_length=32,
            ),
        ),
    ]