# Generated by Django 4.2.7 on 2026-07-04

from django.db import migrations, models
from django.db.models import deletion


def seed_subscription_plans(apps, schema_editor):
    SubscriptionPlan = apps.get_model("marketing", "SubscriptionPlan")
    SubscriptionPlan.objects.get_or_create(
        code="haircut-monthly",
        defaults={
            "name": "Haircut membership",
            "description": "Monthly haircut access for repeat clients.",
            "monthly_amount": "100.00",
            "includes_consultation": False,
            "active": True,
            "sort_order": 1,
        },
    )
    SubscriptionPlan.objects.get_or_create(
        code="haircut-consultation-monthly",
        defaults={
            "name": "Haircut + consultation membership",
            "description": "Monthly haircut access plus consultation support.",
            "monthly_amount": "350.00",
            "includes_consultation": True,
            "active": True,
            "sort_order": 2,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0003_remove_consultation_booking_choice"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=80, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                ("monthly_amount", models.DecimalField(decimal_places=2, max_digits=8)),
                ("includes_consultation", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={"ordering": ["sort_order", "name"]},
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("preferred_date", models.DateField(blank=True, null=True)),
                ("preferred_time", models.CharField(blank=True, max_length=80)),
                ("notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("pending_payment", "Pending payment"),
                            ("active", "Active"),
                            ("cancelled", "Cancelled"),
                            ("failed", "Failed"),
                        ],
                        default="new",
                        max_length=24,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=8)),
                ("currency", models.CharField(default="ZAR", max_length=8)),
                ("m_payment_id", models.CharField(blank=True, max_length=100, unique=True)),
                ("payfast_payment_status", models.CharField(blank=True, max_length=50)),
                ("payfast_signature", models.CharField(blank=True, max_length=128)),
                ("payfast_token", models.CharField(blank=True, max_length=255)),
                ("raw_notify_payload", models.JSONField(blank=True, default=dict)),
                ("active_from", models.DateField(blank=True, null=True)),
                ("next_billing_date", models.DateField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=deletion.PROTECT,
                        related_name="subscriptions",
                        to="marketing.subscriptionplan",
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.RunPython(seed_subscription_plans, migrations.RunPython.noop),
    ]