# Generated by Django 4.2.7 on 2026-07-04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0004_subscription_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=120)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(max_length=50)),
                ("preferred_date", models.DateField(blank=True, null=True)),
                ("preferred_time", models.CharField(blank=True, max_length=80)),
                ("notes", models.TextField(blank=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("website", "Website"),
                            ("meta_whatsapp", "Meta WhatsApp"),
                        ],
                        default="meta_whatsapp",
                        max_length=24,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="new",
                        max_length=24,
                    ),
                ),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="booking_requests",
                        to="marketing.subscriptionplan",
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
    ]