# Generated by Django 4.2.7 on 2026-07-04

from django.db import migrations


def seed_twice_haircut_plan(apps, schema_editor):
    SubscriptionPlan = apps.get_model("marketing", "SubscriptionPlan")
    SubscriptionPlan.objects.get_or_create(
        code="haircut-twice-monthly",
        defaults={
            "name": "2x haircut membership",
            "description": "Monthly access for two haircuts per month.",
            "monthly_amount": "200.00",
            "includes_consultation": False,
            "active": True,
            "sort_order": 2,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0005_bookingrequest"),
    ]

    operations = [
        migrations.RunPython(seed_twice_haircut_plan, migrations.RunPython.noop),
    ]