# Generated by Django 4.2.7 on 2026-07-04

from django.db import migrations


def reorder_subscription_plans(apps, schema_editor):
    SubscriptionPlan = apps.get_model("marketing", "SubscriptionPlan")
    SubscriptionPlan.objects.filter(code="haircut-consultation-monthly").update(sort_order=3)


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0006_subscriptionplan_twice_haircut"),
    ]

    operations = [
        migrations.RunPython(reorder_subscription_plans, migrations.RunPython.noop),
    ]