# Generated by Django 4.2.7 on 2026-07-17 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0008_subscription_user_haircutappointment"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourierShipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True, help_text="ID from courier provider", max_length=255
                    ),
                ),
                ("status", models.CharField(blank=True, max_length=64)),
                ("service_level", models.CharField(blank=True, max_length=80)),
                ("quote_snapshot", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="free_deliveries_per_month",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="includes_free_delivery",
            field=models.BooleanField(default=False),
        ),
    ]
