# Generated by Django 4.2.7 on 2026-07-17 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0010_order_orderline"),
    ]

    operations = [
        migrations.AddField(
            model_name="couriershipment",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shipments",
                to="marketing.order",
            ),
        ),
    ]
