# Generated by Django 6.0.3 on 2026-03-13 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("domain", models.CharField(max_length=255, unique=True)),
                ("schema_name", models.CharField(max_length=100, unique=True)),
                ("created_on", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
