import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = os.environ.get("SECRET_KEY", "replace-me-for-prod")
DEBUG = os.environ.get("DEBUG", "True") == "True"
ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "*").split(",")

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "haircuts",
    "store",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "dissafyt_platform.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    }
]

WSGI_APPLICATION = "dissafyt_platform.wsgi.application"

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

AUTH_PASSWORD_VALIDATORS = []

LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

STATIC_URL = "/static/"
"""
Django settings for dissafyt_platform project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from decimal import Decimal
from pathlib import Path
from urllib.parse import parse_qsl, urlparse

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _env_bool(name: str, default: bool = False) -> bool:
    value = os.environ.get(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def _env_list(name: str, default: str = "") -> list[str]:
    raw = os.environ.get(name, default)
    return [item.strip() for item in raw.split(",") if item.strip()]


def _normalize_host(value: str) -> str:
    value = value.strip()
    if "://" in value:
        parsed = urlparse(value)
        return parsed.hostname or parsed.path
    return value.split("/")[0]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY", "dev-only-insecure-change-me")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool("DEBUG", default=False)

_default_allowed_hosts = ["localhost", "127.0.0.1", ".onrender.com"]
_configured_allowed_hosts = [_normalize_host(host) for host in _env_list("ALLOWED_HOSTS")]
ALLOWED_HOSTS = []
for host in _default_allowed_hosts + _configured_allowed_hosts:
    if host and host not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(host)


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Minimal project apps
    "haircuts",
    "store",
    "payments",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "dissafyt_platform.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "dissafyt_platform.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# On Render, use DATABASE_URL to switch to Postgres
_database_url = os.environ.get("DATABASE_URL")
if _database_url:
    _tmp_postgres = urlparse(_database_url)
    DATABASES["default"] = {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": _tmp_postgres.path.replace("/", ""),
        "USER": _tmp_postgres.username,
        "PASSWORD": _tmp_postgres.password,
        "HOST": _tmp_postgres.hostname,
        "PORT": _tmp_postgres.port or 5432,
        "OPTIONS": dict(parse_qsl(_tmp_postgres.query)),
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Optional human handoff configuration (used by the marketing LLM API)
HUMAN_WHATSAPP_NUMBER = os.environ.get("HUMAN_WHATSAPP_NUMBER", "")

# Consultation-first pricing scaffold.
HOURLY_CONSULTATION_RATE = Decimal(os.environ.get("HOURLY_CONSULTATION_RATE", "250.00"))
HAIRCUT_MONTHLY_RETAINER = Decimal(os.environ.get("HAIRCUT_MONTHLY_RETAINER", "100.00"))
TWICE_HAIRCUT_MONTHLY_RETAINER = Decimal(os.environ.get("TWICE_HAIRCUT_MONTHLY_RETAINER", "200.00"))
FULL_RETAINER_MONTHLY = Decimal(os.environ.get("FULL_RETAINER_MONTHLY", "350.00"))

# Payfast settings for future checkout/subscription integration.
PAYFAST_MERCHANT_ID = os.environ.get("PAYFAST_MERCHANT_ID", "")
PAYFAST_MERCHANT_KEY = os.environ.get("PAYFAST_MERCHANT_KEY", "")
PAYFAST_PASSPHRASE = os.environ.get("PAYFAST_PASSPHRASE", "")
PAYFAST_RETURN_URL = os.environ.get("PAYFAST_RETURN_URL", "")
PAYFAST_CANCEL_URL = os.environ.get("PAYFAST_CANCEL_URL", "")
PAYFAST_NOTIFY_URL = os.environ.get("PAYFAST_NOTIFY_URL", "")
PAYFAST_ENVIRONMENT = os.environ.get("PAYFAST_ENVIRONMENT", "sandbox")
PAYFAST_CURRENCY = os.environ.get("PAYFAST_CURRENCY", "ZAR")
PAYFAST_SUBSCRIPTION_MODE = _env_bool("PAYFAST_SUBSCRIPTION_MODE", default=True)
BOOKING_WEBHOOK_SECRET = os.environ.get("BOOKING_WEBHOOK_SECRET", "")

# Courier Guy configuration (sandbox-first)
COURIER_ENV = os.environ.get("COURIER_ENV", "sandbox")  # 'sandbox' or 'live'
COURIER_ENABLED = _env_bool("COURIER_ENABLED", default=False)
COURIER_API_KEY = os.environ.get("COURIER_API_KEY", "")
COURIER_SANDBOX_BASE_URL = os.environ.get("COURIER_SANDBOX_BASE_URL", "https://api.shiplogic.com")
COURIER_LIVE_BASE_URL = os.environ.get("COURIER_LIVE_BASE_URL", "https://api.portal.thecourierguy.co.za")
COURIER_TIMEOUT_SECONDS = int(os.environ.get("COURIER_TIMEOUT_SECONDS", "15"))

_COURIER_BASE = COURIER_LIVE_BASE_URL if COURIER_ENV.strip().lower() == "live" else COURIER_SANDBOX_BASE_URL
COURIER_BASE_URL = _COURIER_BASE.rstrip("/")

GCP_SERVICE_ACCOUNT_FILENAME = "dissafyt-fbc95c37d13d.json"
_render_secret_path = Path("/etc/secrets") / GCP_SERVICE_ACCOUNT_FILENAME
_local_secret_path = BASE_DIR / GCP_SERVICE_ACCOUNT_FILENAME
GCP_SERVICE_ACCOUNT_PATH = (
    os.environ.get("GOOGLE_APPLICATION_CREDENTIALS")
    or os.environ.get("GOOGLE_SERVICE_ACCOUNT_FILE")
    or (str(_render_secret_path) if _render_secret_path.exists() else str(_local_secret_path))
)

if GCP_SERVICE_ACCOUNT_PATH and Path(GCP_SERVICE_ACCOUNT_PATH).exists():
    os.environ.setdefault("GOOGLE_APPLICATION_CREDENTIALS", GCP_SERVICE_ACCOUNT_PATH)

MARKETING_AGENT_QUERY_URL = os.environ.get(
    "MARKETING_AGENT_QUERY_URL",
    "https://us-central1-aiplatform.googleapis.com/v1/projects/dissafyt/locations/us-central1/reasoningEngines/6207508948644265984:query",
)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
    "loggers": {
        "django.request": {"handlers": ["console"], "level": "INFO", "propagate": False},
        "dissafyt": {"handlers": ["console"], "level": "INFO", "propagate": False},
    },
}